version: '3'
services:
  web:
    image: mydocker/apache:2.0.0.tudai
    ports:
      - 80:80
    volumes:
     - /home/mariano/work/exa/aulavirtual:/var/www/html
    depends_on:
      - mysqldb
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - SERVICE_PORTS=80
      - LANG=es_AR.utf8
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 128m 
  pgdb:
    image: postgres:9.4
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres      
    ports:
      - 5432:5432  
volumes:
  pgdata: